# Generated by Django 4.1.3 on 2022-11-09 20:08

from django.db import migrations
import ratbotapp.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ratbotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', ratbotapp.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
