# Generated by Django 4.1.3 on 2022-11-09 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ratbotapp', '0004_remove_discorduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='Address',
            field=models.CharField(default=-2020, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discorduser',
            name='Landmark',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discorduser',
            name='Mobile',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discorduser',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discorduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
