# Generated by Django 4.1.3 on 2022-11-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratbotapp', '0006_discorduser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
