# Generated by Django 4.1.3 on 2022-11-09 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ratbotapp', '0008_remove_discorduser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
