# Generated by Django 4.1.6 on 2023-02-14 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratbotapp', '0009_membership_alter_result_date_played_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server_id',
            new_name='guild_id',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_name',
            new_name='guild_name',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='membership_id',
            new_name='membership',
        ),
        migrations.RemoveField(
            model_name='result',
            name='author',
        ),
        migrations.RemoveField(
            model_name='result',
            name='server_id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='result_id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='team_id',
        ),
        migrations.AddField(
            model_name='membership',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ratbotapp.server'),
        ),
        migrations.AddField(
            model_name='result',
            name='staff_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='score',
            name='result',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ratbotapp.result'),
        ),
        migrations.AddField(
            model_name='score',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ratbotapp.team'),
        ),
        migrations.AddField(
            model_name='server',
            name='membership_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='membership_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='team_managers',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_tag',
            field=models.CharField(default='', max_length=10),
        ),
    ]
