# Generated by Django 4.1.6 on 2023-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratbotapp', '0010_rename_server_id_server_guild_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='server_images/'),
        ),
    ]
