# Generated by Django 4.1.6 on 2023-02-27 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratbotapp', '0012_remove_result_staff_id_result_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
