# Generated by Django 4.1.6 on 2023-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratbotapp', '0013_team_followers_team_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='invite_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='members',
            field=models.IntegerField(default=0),
        ),
    ]
