# Generated by Django 4.1.6 on 2023-04-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratbotapp', '0015_userprofile_delete_discorduser_delete_scrim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='game_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='game_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
